curr_dir = pwd2;
cd('../lib/genelib/');
system('make');
cd(curr_dir);
mex -output gui_3D_split_watershed ...
  -I../lib/genelib/ ...
  -L../lib/genelib/ ...
  -L/usr/local/lib ...
  -lmyers ...
  gui_3D_split_watershed.mex.c

