function make_mex_here()

if(isunix)
  curr_dir = pwd2;
  cd('../lib/genelib/');
  system('make');
  cd(curr_dir);
  mex -output gui_3D_split_watershed ...
    -I../lib/genelib/ ...
    -L../lib/genelib/ ...
    -L/usr/local/lib ...
    -lmyers ...
    gui_3D_split_watershed.mex.c
end

if(ispc)
  curr_dir = pwd2;
  cd('../lib/genelib/src_win');
  mex -output ../../../proofreading_gui/gui_3D_split_watershed ...
    -I../src_win/ ...
    -L/usr/local/lib ...
    -Dinline=  ...
    -DG_OS_WIN32= ...
    ../../../proofreading_gui/gui_3D_split_watershed.mex.c ...
    utilities.c tiff_io.c tiff_image.c image_lib.c water_shed.c draw_lib.c level_set.c ...
    contour_lib.c
  cd(curr_dir);
end

mex assign_superpixel_from_3D_split.cpp

return
end
