function [err, err_msg] = send_email_python(gmailUser, gmailPassword, recipient, ...
  subject, text, attachment_file_paths)
% [err, err_msg] = send_email_python(gmailUser, gmailPassword, recipient, ...
%   subject, text, attachments)
% Send email via python gmail
%
% Shiv N. Vitaladevuni
% Janelia Farm Research Campus, HHMI
%

global code_dir

if(nargin<=5)
  sys_com = ['python -c "', ...
    'import sys; ', ...
    'sys.path = [''', code_dir, 'lib/python_email''] + sys.path; ', ...
    'import py_email; ', ...
    'py_email.sendMail(', ...
    '\"', gmailUser, '\"', ...
    ',\"', gmailPassword, '\"', ...
    ',\"', recipient, '\"', ...
    ',\"', subject, '\"', ...
    ',\"', text, '\"', ...
    ');"'];
  
  [err, err_msg] = system(sys_com);
else
  attachments = ['[''', attachment_file_paths{1}, ''''];
  for i = 2:length(attachment_file_paths)
    attachments = [attachments, ', ''', attachment_file_paths{i}, '''']; %#ok<AGROW>
  end
  attachments = [attachments, ']'];

  sys_com = ['python -c "', ...
    'import sys; ', ...
    'sys.path = sys.path + [''', code_dir, 'lib/python_email'']; ', ...
    'import py_email; ', ...
    'py_email.sendMailA(', ...
    '\"', gmailUser, '\"', ...
    ',\"', gmailPassword, '\"', ...
    ',\"', recipient, '\"', ...
    ',\"', subject, '\"', ...
    ',\"', text, '\"', ...
    ',', attachments, ...
    ');"'];
  
  [err, err_msg] = system(sys_com);
end

return;
end
