function make_mex_here()

mex compute_neighbor_intensity_histogram.cpp
mex -output erode3 erode3.mex.cpp
mex compute_neighbor_intensity_histogram_norm.cpp
mex hist2.cpp
mex -output dilate3 dilate3.mex.cpp

mex -output medfilt3 ...
  CFLAGS="\$CFLAGS -O3" ...
  medfilt3.mex.cpp

mex -output interval_sum ...
  CFLAGS="\$CFLAGS -O3" ...
  interval_sum.mex.cpp

mex -output draw_segment_boundaries_2D ...
  CFLAGS="\$CFLAGS -O3" ...
  draw_segment_boundaries_2D.mex.cpp

mex draw_segment_boundaries_c.cpp
mex pyramid_hist2.cpp
mex -output merge_sorted_list_for_no_overlap ...
  merge_sorted_list_for_no_overlap.mex.cpp

mex -output compute_rand_score ...
  CFLAGS="\$CFLAGS -O3" ...
  compute_rand_score.mex.cpp

mex -output combnk_knuth ...
  CFLAGS="\$CFLAGS -O3" ...
  combnk_knuth.mex.cpp
return
end
