function make_mex_here()

mex -output compare_label_stacks_bp2 ...
  -I../lib/segbench/Util ...
  -L../lib/segbench/Util/build/x86_64_linux ...
  -lutil ...
  -I"../lib/segbench/CSA++" ...
  -L"../lib/segbench/CSA++/build/x86_64_linux" ...
  -lcsa ...
  compare_label_stacks_bp2.mex.cpp

return
end
