function make_tile_align_deformable_mesh()
if(isunix)
  mex -output tile_align_deformable_mesh ...
    -I../../lib/fftw-3.2/include ...
    -L../../lib/fftw-3.2/.libs ...
    -lfftw3 ...
    tile_align_deformable_mesh.mex.cpp...
    dmesh.cpp
end

if(ispc)
  mex -output tile_align_deformable_mesh ...
    -I../../lib/fftw-3.2/include ...
    -L../../lib/fftw-3.2/lib ...
    -D_FOR_WINDOWS_ ...
    -lfftw3-3 -lfftw3f-3 -lfftw3l-3 ...
    tile_align_deformable_mesh.mex.cpp...
    dmesh.cpp
end

return
end
