function transFunc = createTransformFunctionQuadratic2(polyParam)

%X in [P D]
%polyParam in [D 6]

funcStrCtl = ['@(X) %f * X(:, 1) .^ 2  + %f * X(:,2).^2 ' ...
    '+ %f * X(:,1) .* X(:, 2) ' ...
    '+ %f * X(:, 1) + %f * X(:, 2) '...
    '+ %f'];

transFunc = eval(sprintf(funcStrCtl, polyParam(1), polyParam(2),...
    polyParam(3), polyParam(4), polyParam(5), polyParam(6)));