function make_mex_here()

mex -output get_connected_components_c ...
  -largeArrayDims ...
  get_connected_components.mex.cpp

mex -output get_minimum_spanning_tree ...
  -largeArrayDims ...
  get_minimum_spanning_tree.mex.cpp

return
end
