function make_segment_cascade()
mex -output segment_cascade ...
    -I../lib/merge_sets ...
    -L../lib/merge_sets ...
    -lmerge_sets ...
    -D__DEBUG__ ...
    CFLAGS="\$CFLAGS -O3" ...
    segment_cascade.mex.cpp
return;
end
