function make_segmentation_from_superpixels_mean_boundary_value_RAG()
mex -output segmentation_from_superpixels_mean_boundary_value_RAG ...
    -I../lib/merge_sets ...
    -L../lib/merge_sets ...
    -lmerge_sets ...
    CFLAGS="\$CFLAGS -O3" ...
    segmentation_from_superpixels_mean_boundary_value_RAG.mex.cpp
%     -DDEBUG_ ...
%     -D__PROFILE__
return;
end
