function make_merge_mitochondria_to_mother_cell()
mex -output merge_mitochondria_to_mother_cell ...
    -I../lib/merge_sets ...
    -L../lib/merge_sets ...
    -lmerge_sets ...
    -D__DEBUG_ ...
    CFLAGS="\$CFLAGS -O3" ...
    merge_mitochondria_to_mother_cell.mex.cpp
%     -D__PROFILE__
return;
end
