function make_segmentation_from_superpixels_mean_boundary_value_RAG2()
mex -output segmentation_from_superpixels_mean_boundary_value_RAG2 ...
    -I../lib/merge_sets ...
    -L../lib/merge_sets ...
    -lmerge_sets ...
    CFLAGS="\$CFLAGS -O3" ...
    segmentation_from_superpixels_mean_boundary_value_RAG2.mex.cpp ...
%     -D__DEBUG__
return;
end
