function [features, label_pairs] = ...
  get_linkage_features_overlap_area_shrink_LS(...
  label_map_1, image_1, label_map_2, image_2, transforms_tp, transforms_tp_rev)
% get_linkage_features_overlap_hist_shrink_LS(config)
%
% Shiv N. Vitaladevuni
% Janelia Farm Research Campus, HHMI
%

label_map_1(image_1<0.5) = 0;
label_map_2(image_2<0.5) = 0;

region_overlap_features = [];
region_overlap_features_rev = [];
if(~( isempty(label_map_1) || ...
    isempty(label_map_2) || ...
    isempty(transforms_tp) || ...
    isempty(transforms_tp.transforms) || ...
    isempty(transforms_tp.map_mask) || ...
    size(transforms_tp.transforms, 2)<=4 || ...
    size(transforms_tp_rev.transforms, 2)<=4))
  
  fprintf('Computing linkage area features between segment maps ...\n');
  region_overlap_features = ...
    collect_seg_overlap_stats_area_paffine(...
    uint32(label_map_1), ...
    uint32(label_map_2), ...
    uint8(255*image_1), uint8(255*image_2), ...
    transforms_tp.map_mask, transforms_tp.transforms);
end
if(~( isempty(label_map_1) || ...
    isempty(label_map_2) || ...
    isempty(transforms_tp_rev) || ...
    isempty(transforms_tp_rev.transforms) || ...
    isempty(transforms_tp_rev.map_mask) || ...
    size(transforms_tp_rev.transforms, 2)<=4 || ...
    size(transforms_tp.transforms, 2)<=4))
  
  fprintf('Computing linkage area features between segment maps in reverse...\n');
  region_overlap_features_rev = ...
    collect_seg_overlap_stats_area_paffine(...
    uint32(label_map_2), ...
    uint32(label_map_1), ...
    uint8(255*image_2), uint8(255*image_1), ...
    transforms_tp_rev.map_mask, transforms_tp_rev.transforms);
end
      
if(~isempty(region_overlap_features_rev))
  region_overlap_features = [region_overlap_features; ...
    region_overlap_features_rev(:, [2 1 3:end])];
end

if(isempty(region_overlap_features))
  features = [];
  label_pairs = [];
else
  features = region_overlap_features(:, 3:end);
  label_pairs = region_overlap_features(:,1:2);
end
return
end
