function make_mex_here()

mex collect_area_overlap_features_c.cpp

mex -output collect_area_overlap_features_piecewise_affine_map_c...
  CFLAGS="\$CFLAGS -O3" ...
  collect_area_overlap_features_piecewise_affine_map_c.cpp

mex -output collect_segment_overlap_stats_interior_hist ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_segment_overlap_stats_interior_hist.mex.cpp

mex -output collect_seg_overlap_stats_interior_hist_paffine ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_seg_overlap_stats_interior_hist_paffine.mex.cpp

mex -output collect_seg_overlap_stats_area_paffine ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_seg_overlap_stats_area_paffine.mex.cpp

mex -output get_linkage_graph_from_seg_2_body_map ...
  get_linkage_graph_from_seg_2_body_map.mex.cpp

mex -output get_lists_of_bodies_to_create_dummy_segments_for ...
  get_lists_of_bodies_to_create_dummy_segments_for.mex.cpp

mex -output get_sec_seg_2_body_map_from_links_3D_with_dummy ...
  -I../lib/merge_sets ...
  get_sec_seg_2_body_map_from_links_3D_with_dummy.mex.cpp 

mex -output get_sec_seg_2_body_map_from_links_3D_with_dummy_seeded_seg ...
  -I../lib/merge_sets ...
  get_sec_seg_2_body_map_from_links_3D_with_dummy_seeded_seg.mex.cpp 

mex -output dump_linear_program_p3 ...
  dump_linear_program_p3.mex.cpp

mex -output dump_linear_program_p3_v2 ...
  dump_linear_program_p3_v2.mex.cpp

mex -output get_ineq_TUM_2LDH_MIAS_v3 ...
  CFLAGS="\$CFLAGS -O3" ...
  -I../lib/merge_sets ...
  get_ineq_TUM_2LDH_MIAS_v3.mex.cpp

mex -output get_ineq_TUM_2LDH_MIAS_v4 ...
  CFLAGS="\$CFLAGS -O3" ...
  -I../lib/merge_sets ...
  get_ineq_TUM_2LDH_MIAS_v4.mex.cpp

return
end
