function make_mex_file_input_output()

mex -output fwrite_raw_array_mex ...
  -I./ ...
  -L./ ...
  -liput ...
  fwrite_raw_array_mex.mex.cpp

mex -output fread_raw_array_mex ...
  -I./ ...
  -L./ ...
  -liput ...
  fread_raw_array_mex.mex.cpp

return
end
