function make_mex_here()

mex -output collect_segment_pair_stats_mean_boundary ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_segment_pair_stats_mean_boundary.mex.cpp

mex -output collect_segment_pair_stats_boundary_hist ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_segment_pair_stats_boundary_hist.mex.cpp

mex -output collect_segment_pair_stats_boundary_band_hist ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_segment_pair_stats_boundary_band_hist.mex.cpp

mex -output collect_segment_stats_interior_hist ...
  CFLAGS="\$CFLAGS -O3" ...
  collect_segment_stats_interior_hist.mex.cpp

mex -output relabel_connected_components_2D ...
  CFLAGS="\$CFLAGS -O3" ...
  relabel_connected_components_2D.mex.cpp

make_remove_merged_boundaries_2D();

make_remove_merged_boundaries_3D();

return;
end
